language: node_js
node_js:
  - "15"
  - "14"
  - "12"
  - "10"
  - "9"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "4"
    - node_js: "iojs"
    - node_js: "0.12"
    - node_js: "0.10"
    - node_js: "0.8"
before_install:
  - 'nvm install-latest-npm'
sudo: false
